### ISSUE TITLE
Failed installing: opentri

### ISSUE THREAD

**Issue by ghost** [pspdev/psptoolchain#105]
It seems that one of the CFLAGS options in opentri's makefile is hitting a bug in GCC. This can be worked around by simply commenting out the proper line.

Should anything be done about this? We could either fork the repo and make the fix, pointing opentri.sh to the new repo, or we could add a sed command to opentri.sh to work around the bug.

I think the best solution long term would be to port the toolchain to a newer version of GCC that doesn't have this bug.

**Comment by MilanOzg** [comment]
There are no CFLAGS in my opentri.sh. Is this normal or did it already get fixed because i'm still getting issues installing opentri.

**Comment by carstene1ns** [comment]
Fixed with upgrading gcc.
