### ISSUE TITLE
psp-g++ error: ‘to_string’ is not a member of ‘std’

### ISSUE THREAD

**Issue by GeoVa19** [pspdev/psptoolchain#108]
Yet I'm compiling with either `std=c++11` or `std=c++14`. There is an implementation of std::to_string under $PSPDEV/psp/include/c++/5.4.0/bits/basic_string.h, but all the code is under the preprocessor directive: `#if __cplusplus >= 201103L && defined(_GLIBCXX_USE_C99)`. Any way to define  _GLIBCXX_USE_C99 by default?

I'm using the version 5.4.0 from pull request https://github.com/pspdev/psptoolchain/pull/90.

In the past I also used the version this repository provides, and I had the same issue.

**Comment by davidgfnet** [comment]
Could you test on gcc 8.3 at:
https://github.com/mrneo240/psptoolchain
and report back? I'm not sure what's causing this really ;)

**Comment by dbeef** [comment]
Bundled GCC has been updated to 9.3.0. Could you re-install the toolchain and report whether your problem still exist?

**Comment by GeoVa19** [comment]
I wrote this sample code:

`#include <iostream>
#include <string>

int main() {
    auto a = 10;
    std::string a_str = std::to_string(a);
    return 0;
}
`
I compiled it with `psp-g++ string.cpp -std=c++2a` but still, same problem. The compiler says:

`error: 'to_string' is not a member of 'std'; did you mean 'u32string'?`

**Comment by dbeef** [comment]
You can paste CPP code like this:

![image](https://user-images.githubusercontent.com/13459304/79644833-c30cad00-81ab-11ea-84b9-ab830af4ae3d.png)

Which is rendered as:

```cpp
int main()
{}
```

Anyways, I did some searching through GCC's `basic_string.h`, and it looks that `to_string` methods are visible only when underlying C library is GNU libc, here's `to_string` declaration:

```cpp

#if _GLIBCXX_USE_C99_STDIO
  // NB: (v)snprintf vs sprintf.

  // DR 1261.
  inline string
  to_string(int __val)
  { return __gnu_cxx::__to_xstring<string>(&std::vsnprintf, 4 * sizeof(int),
					   "%d", __val); }

  inline string
  to_string(unsigned __val)
  { return __gnu_cxx::__to_xstring<string>(&std::vsnprintf,
					   4 * sizeof(unsigned),
					   "%u", __val); }

  inline string
  to_string(long __val)
  { return __gnu_cxx::__to_xstring<string>(&std::vsnprintf, 4 * sizeof(long),
					   "%ld", __val); }

  inline string
  to_string(unsigned long __val)
  { return __gnu_cxx::__to_xstring<string>(&std::vsnprintf,
					   4 * sizeof(unsigned long),
					   "%lu", __val); }

  inline string
  to_string(long long __val)
  { return __gnu_cxx::__to_xstring<string>(&std::vsnprintf,
					   4 * sizeof(long long),
					   "%lld", __val); }

  inline string
  to_string(unsigned long long __val)
  { return __gnu_cxx::__to_xstring<string>(&std::vsnprintf,
					   4 * sizeof(unsigned long long),
					   "%llu", __val); }

  inline string
  to_string(float __val)
  {
    const int __n = 
      __gnu_cxx::__numeric_traits<float>::__max_exponent10 + 20;
    return __gnu_cxx::__to_xstring<string>(&std::vsnprintf, __n,
					   "%f", __val);
  }

  inline string
  to_string(double __val)
  {
    const int __n = 
      __gnu_cxx::__numeric_traits<double>::__max_exponent10 + 20;
    return __gnu_cxx::__to_xstring<string>(&std::vsnprintf, __n,
					   "%f", __val);
  }

  inline string
  to_string(long double __val)
  {
    const int __n = 
      __gnu_cxx::__numeric_traits<long double>::__max_exponent10 + 20;
    return __gnu_cxx::__to_xstring<string>(&std::vsnprintf, __n,
					   "%Lf", __val);
  }
#endif // _GLIBCXX_USE_C99_STDIO

```

This could be solved on the psptoolchain side either by updating bundled newlib (although I am not sure of that) or by applying patch removing these guards in few places. 
Relevant discussion:
https://gcc.gnu.org/legacy-ml/gcc-patches/2015-11/msg01808.html

Not closing this, as I'm going to actually try updating newlib soon.

**Comment by sharkwouter** [comment]
Just to add to this, I ran into this just now.

**Comment by stefanmielke** [comment]
Also ran into this on https://github.com/diasurgical/devilutionX/pull/1918. Had to change all to_string() calls to snprintf, but that also doesn't exist if using g++.

**Comment by carstene1ns** [comment]
@stefanmielke: can you try using newlib from [3.3.0 branch](https://github.com/pspdev/newlib/compare/newlib-3.3.0-psp)? I never tested it thoroughly, but maybe is enough.

**Comment by stefanmielke** [comment]
> @stefanmielke: can you try using newlib from [3.3.0 branch](https://github.com/pspdev/newlib/compare/newlib-3.3.0-psp)? I never tested it thoroughly, but maybe is enough.

@carstene1ns, should I just copy the includes, or rebuild the whole toolchain pointing to this branch?

**Comment by carstene1ns** [comment]
Unfortunatly this involves rebuilding stage 2 gcc as well.
However, I doubt it will work. Might really need to patch gcc here.

**Comment by stefanmielke** [comment]
It seems to have worked, unfortunately had this side effect:

```
/usr/local/pspdev/psp/lib/libSDL.a(SDL_string.o): In function `SDL_strupr':
/home/stefanmielke/dev/psp/psptoolchain/build/psplibraries/build/SDL-1.2.15/./src/stdlib/SDL_string.c:385: undefined reference to `__ctype_ptr__'
/home/stefanmielke/dev/psp/psptoolchain/build/psplibraries/build/SDL-1.2.15/./src/stdlib/SDL_string.c:386: undefined reference to `__ctype_ptr__'
/usr/local/pspdev/psp/lib/libSDL.a(SDL_string.o): In function `SDL_strlwr':
/home/stefanmielke/dev/psp/psptoolchain/build/psplibraries/build/SDL-1.2.15/./src/stdlib/SDL_string.c:397: undefined reference to `__ctype_ptr__'
/home/stefanmielke/dev/psp/psptoolchain/build/psplibraries/build/SDL-1.2.15/./src/stdlib/SDL_string.c:398: undefined reference to `__ctype_ptr__'
/usr/local/pspdev/psp/lib/libSDL.a(SDL_string.o): In function `SDL_ScanUnsignedLong':
/home/stefanmielke/dev/psp/psptoolchain/build/psplibraries/build/SDL-1.2.15/./src/stdlib/SDL_string.c:83: undefined reference to `__ctype_ptr__'
/usr/local/pspdev/psp/lib/libSDL.a(SDL_string.o):/home/stefanmielke/dev/psp/psptoolchain/build/psplibraries/build/SDL-1.2.15/./src/stdlib/SDL_string.c:83: more undefined references to `__ctype_ptr__' follow
```

**Comment by carstene1ns** [comment]
This is unfortunately a side-effect of updating the c library. :/
You will need to rebuild sdl as well.

**Comment by stefanmielke** [comment]
I changed the newlib stage and rebuilt the whole pipeline to get that error.
Do I need to change anything else?

**Comment by carstene1ns** [comment]
Clone just the psplibraries repo and run `./libraries.sh SDL`.

**Comment by stefanmielke** [comment]
different errors now:

```/usr/local/pspdev/psp/sdk/lib/libpspirkeyb.a(iniparser.o): In function `strcrop':
iniparser.c:(.text+0x10c): undefined reference to `__ctype_ptr__'
iniparser.c:(.text+0x114): undefined reference to `__ctype_ptr__'
/usr/local/pspdev/psp/sdk/lib/libpspirkeyb.a(iniparser.o): In function `strlwc.part.0':
iniparser.c:(.text+0x160): undefined reference to `__ctype_ptr__'
iniparser.c:(.text+0x164): undefined reference to `__ctype_ptr__'
/usr/local/pspdev/psp/sdk/lib/libpspirkeyb.a(iniparser.o): In function `iniparser_new':
(.text+0xdd8): undefined reference to `__ctype_ptr__'
/usr/local/pspdev/psp/sdk/lib/libpspirkeyb.a(iniparser.o):(.text+0xe00): more undefined references to `__ctype_ptr__' follow```

**Comment by carstene1ns** [comment]
I know it is a bit tedious, but you need the same for every other lib as well.
(just `./libraries.sh pspirkeyb [other libs you use]`)

**Comment by stefanmielke** [comment]
That one more did the trick, thanks!

Do you have a way to push these changes so we can automate this build? Not sure what I'd need to do here.

**Comment by carstene1ns** [comment]
First of all: Thank you for your patience! :)

What would need to be done is testing the updated newlib on hardware. Does your project run now?
Then I can switch branches easily.

**Comment by stefanmielke** [comment]
Well, it _builds_, not really runs though (investigating why now)

Although it only worked on PPSSPP and crashed on real hardware (I think it's something due to the ways it handles files, as we use StormLib).

**Comment by carstene1ns** [comment]
I guess I need to try a basic example then, however, currently no access to a PSP. :/

**Comment by stefanmielke** [comment]
Looks like some of the samples I've tested are working, unfortunately I have no SDL samples to test (btw kernel/fileio is crashing).

**Comment by sharkwouter** [comment]
I know this game uses SDL, but I'm not sure if it still builds, since it isn't updated much: https://github.com/sergiou87/open-supaplex

**Comment by stefanmielke** [comment]
> I know this game uses SDL, but I'm not sure if it still builds, since it isn't updated much: https://github.com/sergiou87/open-supaplex

Same problem mine have. Just a black screen forever (no crashes). Both on PPSSPP and real hardware.

**Comment by wally4000** [comment]
Fixed in current toolchain
