### ISSUE TITLE
Multiple libraries only install after running psplibraries a second time

### ISSUE THREAD

**Issue by sharkwouter** [pspdev/psptoolchain#112]
When building the toolchain in the pspdev-docker container, the following libraries are not installed:
```
Failed installing: angelscript libpng openal opentri pixman SDL_image SDL_ttf
```
If I run psplibraries again in the container some of the libraries which failed before install just fine. This was the result:
```
Failed installing: angelscript openal SDL_image SDL_ttf
```
So libpng, opentri and pixman install just fine the second time. This leads me to believe that psplibraries installs the libraries in the wrong order. I will be looking into this. I've attached the full build log of the psp toolchain.
[log.txt](https://github.com/pspdev/psptoolchain/files/4497808/log.txt)

**Comment by sharkwouter** [comment]
Pixman fails on the following error:
```
[91mutils.c:25:10: fatal error: png.h: No such file or directory
   25 | #include <png.h>
      |          ^~~~~~~
compilation terminated.
```
It needs libpng to be present.

**Comment by sharkwouter** [comment]
Libpng failed on the following error:
```
Couldn't install dependency zlib, aborting.
Failed installing libpng!
```
It needs zlib to be already installed.

**Comment by sharkwouter** [comment]
Opentri needs zlib as well:
```
Couldn't install dependency zlib, aborting.
Failed installing opentri!
```

**Comment by sharkwouter** [comment]
I have fully confirmed my suspicions now. I made a slightly modified version of the Dockerfile which installs the full toolchain, but skips the libraries step. Then I libraries.sh in that after renaming zlib.sh to 001-zilb.sh and libpng.sh to 002-libpng.sh and I got the following result:
```
Failed installing: angelscript openal SDL_image SDL_ttf
```
Which means it totally was the order in which the libraries would be installed.

Now for the solution, that is a bit more difficult. I think my little hack is not a good solution, because it breaks the install check scripts and be annoying to maintain.

**Comment by sharkwouter** [comment]
I've changed sh to bash on the following line in the common.sh script in psplibraries:
https://github.com/pspdev/psplibraries/blob/e5cb9073a74645d5e38dfcecd559d1043b1708ac/common.sh#L34
This was the result when installing on a fresh psptoolchain without psplibraries installed:
```
Failed installing: SDL_image SDL_ttf
```
So this is it, the fix. The container is based on Ubuntu and doesn't have bash as sh.

**Comment by wally4000** [comment]
Wouldn't it be more ideal to parse $SHELL instead of directly calling bash?

**Comment by sharkwouter** [comment]
I don't think it is. These scripts are clearly targetted towards bash, but $SHELL could be anything. It may work in zsh, though, but I don't think supporting more than one shell has much of a benefit for us. Most systemd systems either have bash already installed or easy access to it.

**Comment by sharkwouter** [comment]
@wally4000 I thought about it some more and I realize that it technically doesn't matter whether you use $SHELL or bash, the result will be the same, since the main script has ``#!/bin/bash`` at the top. I still prefer being specific, though, and using bash instead.
