### ISSUE TITLE
Linking fails when using a CPP library

### ISSUE THREAD

**Issue by sharkwouter** [pspdev/psptoolchain#122]
When testing a library I was building for PSP, I found out that loading it causes linking errors. It is the following library: https://github.com/sharkwouter/jsoncpp-psp

The linking errors are the following:
```
[100%] Linking CXX executable hello_world
/usr/bin/cmake -E cmake_link_script CMakeFiles/hello_world.dir/link.txt --verbose=1
/usr/local/pspdev/bin/psp-g++   -std=c++11   CMakeFiles/hello_world.dir/main.cpp.obj  -o hello_world -ljsoncpp -lg -lc -lpspdebug -lpspctrl -lpspsdk         -lpspnet -lpspnet_inet -lpspnet_apctl -lpspnet_resolver -lpspaudiolib         -lpsputility -lGL         -lpspvfpu -lpspdisplay -lpsphprm -lpspirkeyb         -lpsprtc -lpspaudio -lpspvram  -lpspgu -lpspge -lpspuser         -L/usr/local/pspdev/psp/sdk/lib -L/usr/local/pspdev/lib 
/usr/local/pspdev/lib/gcc/psp/9.3.0/../../../../psp/lib/libc.a(_open.o): In function `_open':
(.text+0x70): undefined reference to `sceIoOpen'
/usr/local/pspdev/lib/gcc/psp/9.3.0/../../../../psp/lib/libc.a(setsockopt.o): In function `getsockopt':
(.text+0x40): undefined reference to `sceNetInetGetsockopt'
/usr/local/pspdev/lib/gcc/psp/9.3.0/../../../../psp/lib/libc.a(setsockopt.o): In function `getsockopt':
(.text+0x84): undefined reference to `sceNetInetGetErrno'
/usr/local/pspdev/lib/gcc/psp/9.3.0/../../../../psp/lib/libc.a(setsockopt.o): In function `setsockopt':
(.text+0xe8): undefined reference to `sceNetInetSetsockopt'
/usr/local/pspdev/lib/gcc/psp/9.3.0/../../../../psp/lib/libc.a(setsockopt.o): In function `setsockopt':
(.text+0x178): undefined reference to `sceNetInetGetErrno'
/usr/local/pspdev/lib/gcc/psp/9.3.0/../../../../psp/lib/libc.a(_stat.o): In function `_stat':
(.text+0x38): undefined reference to `sceIoGetstat'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/hello_world.dir/build.make:87: hello_world] Error 1
make[2]: Leaving directory '/home/wouter/Sources/freegemas/hellopsp/Tutorial_2_Hello_World/psp'
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/hello_world.dir/all] Error 2
make[1]: Leaving directory '/home/wouter/Sources/freegemas/hellopsp/Tutorial_2_Hello_World/psp'
make: *** [Makefile:87: all] Error 2
```
This occured while building this project: https://github.com/sharkwouter/hello-json-cpp

Adding ``-lstdc++`` to my link targets solved this, even though the linking is being done by psp-g++.

Reproducing this can be done with the following steps if you have psp-pacman installed: 
- Clone repo of the library with: ``git clone https://github.com/sharkwouter/jsoncpp-psp.git``
- Go into the directory: ``cd jsoncpp-psp``
- Build and install the library: ``psp-makepkg -i``
- Clone the example repo: ``git clone https://github.com/sharkwouter/hello-json-cpp.git``
- Go into the directory: ``cd hello-json-cpp``
- Remove ``stdc++`` from ``target_link_libraries`` in ``CMakeLists.txt`` with a text editor
- Make a build directory: ``mkdir build && cd build``
- Build it: ``psp-cmake .. && make``
- Enjoy the linking errors.

If you leave ``stdc++`` in ``CMakeLists.txt``, there will be no linking errors.

**Comment by wally4000** [comment]
Is this still an issue with the new toolchain? :)
