### ISSUE TITLE
toolchain-sudo.sh doesn't work on macOS with brew because running brew as root has been no longer unsupported

### ISSUE THREAD

**Issue by yaplus** [pspdev/psptoolchain#134]
When trying to install the toolchain to `/usr/local` on Mac with Homebrew, an error
```
Couldn't find dependencies:
  - libarchive
  - libssl
```
has occurred in `depends/check-dependencies.sh`, because running brew as root has been no longer unsupported.

The error seems to be caused by the following line, which is running `brew --version` as root in `toolchain-sudo.sh`:
https://github.com/pspdev/psptoolchain/blob/79b1cf8b0cafd4c1b4f8aaee21bbb95d66f7c547/depends/check-dependencies.sh#L96-L98

**Comment by carstene1ns** [comment]
So `--version` works not, but getting the prefix works?

I think using sudo might be a bit overkill then. We could use `command -v brew` to check instead.

**Comment by carstene1ns** [comment]
Okay, looks like we can get away with this:
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/brew.sh#L439
