### ISSUE TITLE
does not support ARM CPU on raspberry pi 3 b+

### ISSUE THREAD

**Issue by meeeeeeeeeeeeeeee** [pspdev/psptoolchain#138]
after deleting the old files from trying to install using this guide  https://wololo.net/talk/viewtopic.php?t=3635 and extracting from the zip on here i tyied runing the .sh script and this is the error i got:

pi@raspberry-pi:~/psptoolchain $ sudo ./toolchain-sudo.sh Couldn't find dependencies: - libcurl - gpgme - cmake - tclsh - doxygen - libarchive - libtoolize ../depends/check-dependencies.sh: Failed. ERROR: Could not run the toolchain script.

some of these will install but libcurl gpgme tclsh libarchive and libtoolize will not install even after running sudo apt update

this needs to be fixed because my PC is broken right now and my raspberry pi is all i have to run linux on until i get the parts to fix it

**Comment by John-K** [comment]
There is no reason why those packages should not install on a RaspberryPi - what distro are you using on your RPi?

**Comment by meeeeeeeeeeeeeeee** [comment]
Raspbian 32 bit

**Comment by John-K** [comment]
what does `sudo apt-get install libcurl gpgme cmake tclsh doxygen libarchive libtoolize` do for you?

**Comment by androids7** [comment]
when i run at fedora and this error found:
can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff -NrU3 binutils-2.23.2/bfd/archures.c binutils-2.23.2-patched/bfd/archures.c
|--- binutils-2.23.2/bfd/archures.c     2012-09-04 14:53:41.000000000 +0200
|+++ binutils-2.23.2-patched/bfd/archures.c     2020-04-23 17:57:30.297522944 +0200
--------------------------
File to patch:
-------------------------------------
then  still stop at here

**Comment by wally4000** [comment]
No further comments, this issue is now closed :)
