### ISSUE TITLE
The script should check that the CMake version is >= 3.10.0

### ISSUE THREAD

**Issue by yoanlcq** [pspdev/psptoolchain#141]
This might be just me running an outdated distro, but I'm on Ubuntu 17.04 zesty, and the `cmake` version provided by `apt` is `3.7.2`, which is too low for one of the dependencies (unfortunately I have lost the output log, so I don't know which one it is, but that causes the installation of multiple libraries to fail).

For reference, the latest CMake version is `3.19.2`.

I'm not sure what the best course of action would be here, since I suspect the issue might not occur for recent enough distros.
Furthermore, this might be not this script's responsibility.

I still figured I would mention this though. Maybe the README should hint that installing the latest CMake version manually may be recommended, and/or maybe the script should do a quick `cmake --version` check.

**Comment by sharkwouter** [comment]
Thanks for reporting this, I'm sorry no one got to this. Unfortunately this issue is no longer relevant, so I'm closing it for now.
