### ISSUE TITLE
Include "libusb-compat" as an Arch-based Linux distro dependency

### ISSUE THREAD

**Issue by lagunagfx** [pspdev/psptoolchain#146]
On Arch-based systems **there is no libusb-dev package** since the split between _package_ and _package-dev_ is not used.

Please mention that package _libusb-compat_ provides _/usr/include/usb.h_ as expected by _depends/check_dependencies.sh_.

`sudo pacman -Sy libusb-compat`

I'm running Manjaro.

**Comment by sajattack** [comment]
If you'd like to create a `prepare-archlinux.sh` script, that would be appreciated as a PR. I think that would be a better place than a note in the README.

**Comment by lagunagfx** [comment]
That would be great!. I had been "off the psp" for a while, so I'll check it and get back to you. Please excuse me if I'm a total newbie when it comes to Git etiquette

**Comment by diamant3** [comment]
Maybe this issue can be close because they have the `prepare-arch.sh` script in the [pspdev repo](https://github.com/pspdev/pspdev/blob/master/prepare-arch.sh) or just copy the script here to fix.
