### ISSUE TITLE
Why newlib-1.2.0 instead of newer versions?

### ISSUE THREAD

**Issue by frabert** [pspdev/psptoolchain#148]
Hi! I noticed the scripts compile and install newlib from the 1.2.0 branch, even though a branch 4.1.0 exists. What's the reason?

**Comment by sharkwouter** [comment]
I don't think the work on newer newlib versions was ever completed

**Comment by carstene1ns** [comment]
I am currently lacking the hardware to test this further, however in ppsspp emulator it works.
There are a lot WIP changes scattered around in most repos here. :/

**Comment by frabert** [comment]
I am not familiar with the homebrew scene nor with "alternative" `libc`s, what do newer newlib versions bring?

Also, what hardware is needed to test that newlib is working? Is there a test suite I can try, compile and run on a PSP slim?

**Comment by wally4000** [comment]
Newlib is now latest :)
