### ISSUE TITLE
mkdir: build-psp: File exists ../scripts/004-newlib-1.20.0.sh: Failed error in MacOS while installing the tool chain

### ISSUE THREAD

**Issue by SaiBalaji22** [pspdev/psptoolchain#152]
I'm getting this error while running the tool chain in BigSur
mkdir: build-psp: File exists
../scripts/004-newlib-1.20.0.sh: Failed.
ERROR: Could not run the toolchain script.
How can I resolve it

**Comment by carstene1ns** [comment]
Looks to me like you have an old build folder around. You can delete it and try again.

```
rm -rf build/newlib/build-psp
./toolchain[...].sh 4
```

**Comment by sajattack** [comment]
changing the script to `mkdir -p` would fix this too.
