### ISSUE TITLE
make: *** [all] Error 2 ../scripts/007-gdb.sh: Failed. ERROR: Could not run the toolchain script in macOS when installing toolchain

### ISSUE THREAD

**Issue by SaiBalaji22** [pspdev/psptoolchain#153]

**Comment by carstene1ns** [comment]
This is readline related, needs `sys/ioctl.h` inclusion. Will fix soonish.

**Comment by SaiBalaji22** [comment]
> This is readline related, needs `sys/ioctl.h` inclusion. Will fix soonish.

Can u explain me clearly what should change :)

**Comment by mbarczak** [comment]
Hi @SaiBalaji22 , if you still need it, you can cherry pick [this](https://github.com/mbarczak/psptoolchain/commit/af1a8e0964e98080d12a711ea0811b8e942787cb) commit from my fork for the macOS build to work successfully. Cheers.
