### ISSUE TITLE
Newlib doesn't use the whole space memory

### ISSUE THREAD

**Issue by fjtrujy** [pspdev/psptoolchain#155]
Hello,
As probably some of you know, I'm working to update & improve the PSP toolchain in general.

I was checking how much memory we can allocate using `newlib` and I saw how there was about 1MB of RAM not being accessible from `newlib`.
After some investigation, I saw that problem was that binary was allocated in the middle of the user memory region, more concretely at `0x08900000`, however, the region from where the user can allocate memory starts at `0x08804000`.

This value is set in the `binutils` patch
https://github.com/pspdev/psptoolchain/blob/master/patches/binutils-2.23.2-PSP.patch#L2791

I have changed it to `0x08804000`, and so far in my tests everything worked fine, and most important is that now we can use the whole ram through `malloc`.

The reason why I create this issue, is just to ask the community if there is any specific reason why this was set to `0x08900000`, is there any reason that I'm not aware of?

Finally, I have attached some screenshots (using PPSSPP and PSP-1000) where you can see the amount of memory we can allocate before and after my change.

Before, Maximum `23674860 bytes`
<img width="1072" alt="Screenshot 2021-10-12 at 14 06 04" src="https://user-images.githubusercontent.com/10010409/136953130-e2dab3c4-6f76-405d-8acd-45ef6aa99cc0.png">

After, Maximum `24752108 Bytes`
<img width="1072" alt="Screenshot 2021-10-12 at 01 10 04" src="https://user-images.githubusercontent.com/10010409/136953205-b725e001-3bd1-40a4-8b35-2fbe0f8665eb.png">

Thanks

**Comment by Sal-gamer** [comment]
Psp 2000 or 3000 memory 1MB extra?

**Comment by fjtrujy** [comment]
Closing issue because has been fixed with l latest merges
