### ISSUE TITLE
002-gcc-stage1.sh build failed on macOS 12

### ISSUE THREAD

**Issue by baiXfeng** [pspdev/psptoolchain#157]
Undefined symbols for architecture x86_64:
  "_mips_arch", referenced from:
      ___cxx_global_var_init in gencondmd.o
  "_mips_isa", referenced from:
      ___cxx_global_var_init in gencondmd.o
  "_mips_isa_rev", referenced from:
      ___cxx_global_var_init in gencondmd.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [build/gencondmd] Error 1
make[2]: *** Waiting for unfinished jobs....
7 warnings generated.
rm gcc.pod
make[1]: *** [all-gcc] Error 2
make: *** [all] Error 2
../scripts/002-gcc-stage1.sh: Failed.
ERROR: Could not run the toolchain script.

**Comment by carstene1ns** [comment]
Still on big sur here, need to update and test.

**Comment by fjtrujy** [comment]
Hello @baiXfeng ,
Have you tried after the `refactor` that we have done? Now the main repo for installing `PSPDEV Environment` is:
`https://github.com/pspdev/pspdev`, please do a clean installation.

Thanks

**Comment by baiXfeng** [comment]
@fjtrujy I try to reinstall pspdev on macOS Monterey, but it has an error:
baifeng@BF-MAC pspdev % ./build-all.sh
Couldn't find dependencies:
  - libtoolize
../depends/check-dependencies.sh: Failed.
baifeng@BF-MAC pspdev % brew search libtoolize
==> Formulae
libtool ✔

**Comment by baiXfeng** [comment]
I use pspdev/psptoolchain.git for install, edit ./depends/check-dependencies.sh [libtoolize] to [libtool], it can be continue, but still has error:
xgcc: error: addsf3: No such file or directory
make[2]: *** [addsf3.o] Error 1
make[2]: *** Waiting for unfinished jobs....Mode = sf

xgcc: error: subsf3: No such file or directory
make[2]: *** [subsf3.o] Error 1
Suffix = si\|2\|3
xgcc: error: negsf2: No such file or directory
make[2]: *** [negsf2.o] Error 1
make[1]: *** [all-target-libgcc] Error 2
make: *** [all] Error 2
../scripts/003-gcc-stage1.sh: Failed.
../scripts/001-allegrex.sh: Failed.

**Comment by fjtrujy** [comment]
> I use pspdev/psptoolchain.git for install, edit ./depends/check-dependencies.sh [libtoolize] to [libtool], it can be continue, but still has error: xgcc: error: addsf3: No such file or directory make[2]: *** [addsf3.o] Error 1 make[2]: *** Waiting for unfinished jobs....Mode = sf
> 
> xgcc: error: subsf3: No such file or directory make[2]: *** [subsf3.o] Error 1 Suffix = si|2|3 xgcc: error: negsf2: No such file or directory make[2]: *** [negsf2.o] Error 1 make[1]: *** [all-target-libgcc] Error 2 make: *** [all] Error 2 ../scripts/003-gcc-stage1.sh: Failed. ../scripts/001-allegrex.sh: Failed.

That's funny, it means that you can compile the binutils, but you can't now compile GCC xD, could you please but the whole log?

**Comment by baiXfeng** [comment]
@fjtrujy Of course.
[psptoolchain.log](https://drive.google.com/file/d/1AP47tkxWrpvtjn6pGzX6n5vflHb6gfTD/view?usp=sharing)

**Comment by fjtrujy** [comment]
I'm currently in Monterrey and I just compiled it without any problem.

**Comment by fjtrujy** [comment]
Closing this issue, feel free to re-open if it still not working for you.
