### ISSUE TITLE
build failed when use SDL2_mixer on Ubuntu and macOS

### ISSUE THREAD

**Issue by baiXfeng** [pspdev/psptoolchain#158]
/usr/local/pspdev/lib/gcc/psp/9.3.0/../../../../psp/lib/libSDL2_mixer.a(mixer.o)：在函数‘Mix_LoadWAV_RW’中：
/Users/baifeng/psplibraries/build/SDL_mixer/mixer.c:717：对‘SDL_LoadWAV_RW’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [sdl2-ui] Error 1
make[1]: *** [CMakeFiles/sdl2-ui.dir/all] Error 2
make: *** [all] Error 2

**Comment by baiXfeng** [comment]
@sharkwouter Yah, I was linked, these is my CMakeLists.txt code:
`include_directories($ENV{PSPDEV}/psp/include/SDL2)
	add_definitions(-DLUA_C89_NUMBERS)
	add_executable(${PROJECT_NAME} ${BASIC_SOURCE})
	target_link_libraries(${PROJECT_NAME} PRIVATE
			SDL2
			SDL2_ttf
			SDL2_image
			SDL2_mixer
			freetype
			jpeg
			vorbisidec
			mikmod
			ogg
			png
			m
			z
			c
			GL
			pspvram
			${PSP_LIBRARIES}
	)
	create_pbp_file(
			TARGET ${PROJECT_NAME}
			ICON_PATH ICON0.PNG
			BACKGROUND_PATH NULL
			PREVIEW_PATH NULL
			TITLE ${PROJECT_NAME}
	)
	file(COPY platform/psp/ICON0.PNG DESTINATION ${CMAKE_BINARY_DIR})
	file(COPY assets DESTINATION ${CMAKE_CURRENT_BINARY_DIR})`

**Comment by sharkwouter** [comment]
I have an example which builds here: https://github.com/sharkwouter/panel-pop/blob/f2ed29d230d3ac65f0f2f04218a84b7d0a8c4e41/CMakeLists.txt#L146-L163

SDL2_ttf has some issues, though.

**Comment by baiXfeng** [comment]
@sharkwouter Ah, It work! thank you.

**Comment by sharkwouter** [comment]
Great! Thanks for reporting issues, though, it's useful
