### ISSUE TITLE
prepare-mac-os.sh missing additional dependencies for installation

### ISSUE THREAD

**Issue by BrilliantOne** [pspdev/psptoolchain#161]
The following dependencies are not included in `prepare-mac-os.sh`:
```
gpgme
svn
```
When running `sudo ./toolchain-sudo.sh` the following error is thrown:

```
Couldn't find dependencies:
  - gpgme
  - svn
```

**Comment by fjtrujy** [comment]
This issue has been fixed with the latest refactors.

Thanks
