### ISSUE TITLE
ERROR: Could not run the toolchain script.

### ISSUE THREAD

**Issue by ChineseHotPot** [pspdev/psptoolchain#165]
../../gcc/genhooks.c:199:14: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  199 |       fscanf (f, "%999s", buf);
      |       ~~~~~~~^~~~~~~~~~~~~~~~~
GIMPLE decision tree has 3776 leafs, maximum depth 28 and a total number of 16107 nodes
removed 2476 duplicate tails
GENERIC decision tree has 3511 leafs, maximum depth 13 and a total number of 14666 nodes
removed 2400 duplicate tails
/bin/bash: line 1: 330321 Killed                  build/genautomata ../../gcc/common.md ../../gcc/config/mips/mips.md insn-conditions.md > tmp-automata.c
make[2]: *** [Makefile:2459: s-automata] Error 137
make[1]: *** [Makefile:4410: all-gcc] Error 2
make: *** [Makefile:940: all] Error 2
../scripts/002-gcc-stage1.sh: Failed.
../scripts/001-allegrex.sh: Failed.
ERROR: Could not run the toolchain script.

I got this error info when I run the toolchain-sudo.sh in ubuntu server 20.04 LTS, someone can help me?

**Comment by sajattack** [comment]
looks like your computer ran out of memory.

**Comment by ChineseHotPot** [comment]
> 看起来你的电脑内存用完了。

Thanks, You are right! my server‘s mem is to low. (2GB). It's runing ok when i add one swapfile.

**Comment by ChineseHotPot** [comment]
> looks like your computer ran out of memory.

Thanks, You are right! my server‘s mem is to low. (2GB). It's runing ok when i add one swapfile.

**Comment by sharkwouter** [comment]
Thanks for the update, I'll close this for now. If building the toolchain is an obstacle, there is also a pre-compiled version available. Check out https://pspdev.github.io/
