### ISSUE TITLE
need to add install commands for unhandled dependencies on ubuntu--22.10

### ISSUE THREAD

**Issue by xor32dotcom** [pspdev/psptoolchain#169]
they are 

pip3
gpgme-config
openssl

the fix:
apt install python3-pip
apt install libssl-dev
apt install libgpgme11-dev (i dont know wether the 11 breaks the installer or not, or wether you can run apt install libgpgme-dev without the 11)

bonus: https://flathub.org/apps/details/org.ppsspp.PPSSPP

this flatpakbuild makes it really easy to install PPSSPP on ubuntu

apt install flatpak
sudo flatpak install org.ppsspp.PPSSPP.flatpakref

which can then be ran using sudo flatpak run org.ppsspp.PPSSPP
this new build is really unique because it makes it really easy to install ppsspp without worrying to much about new dependencies as flatpak takes care of them all

would be nice to add a flag to the script --build-ppsspp due to how easy it is to install ( it only takes 2 commands to do so)

**Comment by wally4000** [comment]
Sorry but i'm failing to see what this has to do with the PSP Toolchain if you're trying to build PPSSPP?
