### ISSUE TITLE
Error in Cygwin

### ISSUE THREAD

**Issue by ericavd101** [pspdev/psptoolchain#52]
I just tried psptoolchain in Cygwin for Windows XP. It sopped at configuring mpfr in "002-gcc-stage1.sh". The error message is:

checking for math/round... yes
checking for math/trunc... yes
checking for math/floor... yes
checking for math/ceil... yes
checking for math/rint... yes
checking for long double... yes
checking format of `long double' floating point... IEEE extended, little endian
checking for TLS support... yes
checking for library containing clock_gettime... none required
checking for gmp.h... yes
checking for i686-pc-cygwin-as... as
checking for i686-pc-cygwin-dlltool... dlltool
checking for i686-pc-cygwin-objdump... objdump
checking for DLL/static GMP... DLL
configure: error: gmp.h is a DLL: use --disable-static --enable-shared
Makefile:6218: recipe for target 'configure-mpfr' failed
make[1]: **\* [configure-mpfr] Error 1
make[1]: Leaving directory '/home/ericliao/psptoolchain/build/gcc-4.6.4/build-ps
p'
Makefile:887: recipe for target 'all' failed
make: **\* [all] Error 2
../scripts/002-gcc-stage1.sh: Failed.

**Comment by carstene1ns** [comment]
Stale issue, nowadays likely works with msys or the Linux subsystem of Windows 10
