### ISSUE TITLE
Doesn't compile anything for some reason?

### ISSUE THREAD

**Issue by wxcafe** [pspdev/psptoolchain#53]
I build this toolchain on my computer, and it apparently can't compile /anything/, I don't have a clue why.

![](http://pub.wxcafe.net/screen_0804-1900.png)

**Comment by libcg** [comment]
You are not supposed to invoke psp-gcc directly.

**Comment by wxcafe** [comment]
Alright sorry, I've seen that it's supposed to be used with the custom makefile... 
Thanks.
