### ISSUE TITLE
Failed installing: freetype opentri SDL_ttf

### ISSUE THREAD

**Issue by futurepr0n** [pspdev/psptoolchain#60]
Hi guys,

Recently tried to re-take up PSPDev, been away for a while and looking to get back into it as a hobby.

Just ran the sudo_toolchain.sh but ended up having the following error after all was said and done (or at least, this was the final few lines)

Installation Finished
Failed installing: freetype opentri SDL_ttf

Is there any help that someone may be able to offer me in order to resolve this? Or will these not hinder me much through development?

**Comment by vatomalo** [comment]
try sudo ./toolchain-sudo.sh --export-dynamic pspdev/psp-ports

**Comment by carstene1ns** [comment]
Please try again with recent toolchain.

**Comment by futurepr0n** [comment]
./toolchain.sh: line 33: pspdev/psp-ports-1: division by 0 (error token is "psp-ports-1")
ERROR: Could not run the toolchain script.

**Comment by sharkwouter** [comment]
Try running ``export PSPDEV=/the/location/of/your/psp/toolchain`` before running it.

**Comment by futurepr0n** [comment]
It looks like as stated in another issue I had that this was fixed, and I can install all the libraries successfully! Thank you @sharkwouter @carstene1ns et all

**Comment by carstene1ns** [comment]
No idea where the export-dynamic comes from (looks like compiler/linker option), however is wrong to begin with.
