### ISSUE TITLE
After installing on Debian 8 sample gw/cube makes PSP freeze

### ISSUE THREAD

**Issue by nikmes** [pspdev/psptoolchain#65]
I can confirm that with older version of the SDK the samples work fine. Specificaly the gu/cube sample. Is there any update that i should do in Makefiles or somewhere. I notice that samples that are not using images and textures work fine.

**Comment by DaveeFTW** [comment]
This is an issue I came across too. libgcc for 4.9 does not generate proper software routines for handling double->float conversions. The lazy fix I did was copying over libgcc from an older installation.

**Comment by carstene1ns** [comment]
I also had this problem. I am currently using GCC 4.8.5 rebased from #61, which works fine.

**Comment by nikmes** [comment]
Thyanks. I will also try that.

**Comment by wickles** [comment]
@carstene1ns worked for me, thanks!

**Comment by dbeef** [comment]
As linked PR's are merged, I suspect that the problem is fixed;
however, as we have just updated toolchain to use GCC 9.3.0, please report any persisting problems under:

https://github.com/pspdev/pspsdk/issues/26
