### ISSUE TITLE
Trying to install on Mac OS X 

### ISSUE THREAD

**Issue by stephkno** [pspdev/psptoolchain#66]
It almost installs, but I end up with this vague makefile error:

 make[2]: **\* [html/index.html] Error 1
make[1]: **\* [all-recursive] Error 1
make: **\* [all] Error 2

**Comment by joshdekock** [comment]
where exactly does it error, show a full log.

**Comment by wickles** [comment]
I've been having issues installing on OSX as well. Busy now but will try to get back to this and provide some logs and fixes I've been trying.

**Comment by John-K** [comment]
See Issue #77
