### ISSUE TITLE
[Documentation] Ubuntu package `automake1.9` gone

### ISSUE THREAD

**Issue by Fordi** [pspdev/psptoolchain#68]
Package `automake1.9` no longer exists in Ubuntu; docs should be updated to use `automake1.11`.

An adjustment to the apt command (also ubuntu uses apt now, but apt-get still works) that should be reasonably future-proof is:

```
sudo apt install g++ build-essential autoconf automake `apt-cache search automake1 | cut -d \  -f 1` cmake doxygen bison flex libncurses5-dev libsdl1.2-dev libreadline-dev libusb-dev texinfo libgmp3-dev libmpfr-dev libelf-dev libmpc-dev libfreetype6-dev zlib1g-dev libtool libtool-bin subversion git tcl unzip
```

**Comment by carstene1ns** [comment]
Question is, do we really need an old automake version at all? I was able to build the whole toolchain just fine without it under Arch and Fedora Linux recently.
If nobody has an idea why it is needed nowadays, I suspect the software using it has been updated in the meantime and therefore I am going to open a pull request removing it soon.

**Comment by thePalindrome** [comment]
Other distros still have 1.9 versions available, but I do agree, is there any real reason to require a version that old?

**Comment by carstene1ns** [comment]
No, there is no reason, as mentioned before. There maybe was once, but not anymore. Also the autotools are usually only required when you do not use prepared source tarballs, but git checkouts and such to generate the `./configure` script and `Makefile.in`. So maybe we should provide a pull request to disable it.

Unfortunately, the original developers are not really active here anymore, so there is only a minor chance of merging.

Considering this goes likely out to the whole team via email, I would like to apply for some maintenance work here 😄 for example:
- [updating documentation](https://github.com/carstene1ns/pspsdk/commit/981d7cab12e3ad585e71dc28858c2a1bbb19f8e3)
- merging build fixes
- restructuring and removing cruft
- use Travis CI to test building the toolchain for Linux and Mac OS at least

I would love to receive a @pspdev organization invitation... :+1:

**Comment by loopaware** [comment]
I would gladly sponsor this pspsdk on patreon with a few dollars every month if anybody would like to resume development.

**Comment by suicvne** [comment]
Download automake1.9 manually from the Ubuntu repositories and install the dpkg.

`sudo dpkg -i automake1.9-amd64-xxxx.deb`

That's the easy fix.

**Comment by suicvne** [comment]
And I don't mean to derail or anything but....

![48376183_2250683828547666_498978395527315456_o](https://user-images.githubusercontent.com/861492/50153707-355a3e00-0295-11e9-90e0-4a223657bb4d.jpg)

Here's a peek at libGyro/Elysian VMU running in PPSSPP...I've been working on porting it over but this toolchain is very sensitive. It also doesn't run on real hardware yet for some and apparently psplink isn't building currently.

**Comment by dbeef** [comment]
Specifying automake version has been removed by the following PR's:

https://github.com/pspdev/psptoolchain/pull/87
https://github.com/pspdev/psptoolchain/pull/83

Because of that, closing the issue.
 
> I would love to receive a @pspdev organization invitation... :+1: 
@carstene1ns, I know this issue is more than 3 years old, but do you still fancy to join pspdev? ;)

**Comment by carstene1ns** [comment]
Sure, @dbeef, it has been some time, but the recent activity here is amazing.
Color me interested. I still have some PSP projects ongoing.
