### ISSUE TITLE
newlib-1.20.0 not found

### ISSUE THREAD

**Issue by yoyz** [pspdev/psptoolchain#70]
Why don't we put this required library in a http://pspdev/psptoolchain/tarball directory ?

**Comment by Fighter19** [comment]
Building newlib for me worked fine. Could you please be more precise?
What's the error?

**Comment by yoyz** [comment]
Sorry I have not seen your reply...

newlib-1.20.0 can be built, with the toolchain, it work without a flaw for me too.
For me, what is broken, is the mirror to get newlib ( the wget/curl I have not seek what is used ), I have this issue this morning, and I had it 6 month ago, so I think it is broken on my debian laptop.
And I use git pull this morning, so I should be uptodate.

I have downloaded newlib-1.20 with firefox put it in build directory and launched :
$ ./toolchain.sh 004
And it is ok, but this step, is a little difficult to understand.

**Comment by fcr--** [comment]
What I guess should be changed is the link from `ftp://sources.redhat.com/pub/newlib/newlib-1.20.0.tar.gz` to `http://sources.redhat.com/pub/newlib/newlib-1.20.0.tar.gz` (only changes the protocol to http) in scripts/004-newlib-1.20.0.sh

**Comment by carstene1ns** [comment]
Maybe you should take a look at PR #81.

**Comment by John-K** [comment]
@yoyz can you please re-check now? I just merged #81

**Comment by yoyz** [comment]
Hi, sorry for the lag.
I rebuilt today the whole toolchain on another laptop.
newlib seem to be fix with master branch : 16dc212da5bff10ed8c2c6415cd70531ea60d9b0

Unfortunately, there is othere issue now, related to XXX.tar.gz in html format...
Will open a new PR, this one can be close I think

**Comment by dbeef** [comment]
Closing this issue as right now we have newlib mirrored under:

https://github.com/pspdev/newlib/
