### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by Fighter19** [pspdev/psptoolchain#71]
Using this toolchain results in a Bus Error when using up bigger parts of the memory.
This project:
https://github.com/mafu9/PSPMania
Can be built with MinPSPW.
With MinPSPW it works just fine.
However with this toolchain it runs into a bus error while entering the Song Select screen (Renaming song.h to Song.h in every file might be needed if not done on Windows).
A wild guess is that it's binutils related (As I've seen Daedalus suffering similar issues).
The binary is also 1 MB bigger.
(From 7MB to 8MB)

To test this, the assets have to be downloaded (http://mafu9.blog40.fc2.com/blog-entry-17.html) and be put into the same folder as the executable.

**Comment by Fighter19** [comment]
I found out that this in fact is gcc related.
Using a new gcc version with -O bigger than 0 will make the program crash, however with -O0 the game will run much slower. (i couldn't find which optimization causes the crash, however this is something that happens to more than just this program)

**Comment by John-K** [comment]
To be honest, that sounds like a bug in the game.

**Comment by Fighter19** [comment]
It might be a possibility, although I've also experienced problems with setting breakpoints (inside a while loop).
Also again, it works without any problems with old gcc+binutils, I guess. (I'll try to compile the new toolchain with the old gcc&binutils and see what happens, to exclude that other changes might cause this issue like libraries etc...).
I don't think I ran into any problems for C-programs so far. So this might only apply to C++ programs.
This would also explain why nobody else really runs into those problems.
Also if something runs with -O0 stable it should also run as stable with -O1 or -O2 else the optimization is most likely broken (imo). However I can't reproduce this result anymore.....

**Comment by Fighter19** [comment]
It seems this was related to libpspgum.
After removing "__asm(a0)" from the two lines (in the functions sceGumOrtho and sceGumPerspective), it builds and runs as intended.

Should this be closed here (It's not really related to this repository but rather to pspsdk)?

**Comment by dbeef** [comment]
Please open a PR on pspsdk with suggested changes in pspgum. Closing this issue.
