### ISSUE TITLE
Failed installing: angelscript libmikmod libpng openal opentri pixman SDL_image SDL_mixer

### ISSUE THREAD

**Issue by futurepr0n** [pspdev/psptoolchain#74]
Hi - during install, I was unable to properly install the following as part of running the toolchain:

Failed installing: angelscript libmikmod libpng openal opentri pixman SDL_image SDL_mixer

It seems like it hasnt prevented me from building any helloworld project, but I did have some other old source that did use these libraries and it did not build. Any chance you could offer me any advisement on how to get these?

**Comment by uppfinnarn** [comment]
Please post logs. Nobody can help you from just that.

**Comment by futurepr0n** [comment]
[output.txt](https://github.com/pspdev/psptoolchain/files/628334/output.txt)

I am trying to set up for a vagrant box that will stand up a psp dev environment on its own, and I was hoping at a glance the issue would be noticeable or familiar enough someone would have a quick suggestion! The toolchain still builds but does have some failures along the way. I have the full output attached, but im going to try and narrow down some parts and edit this post to highlight some key areas. 

I really appreciate the help! Thanks

**Comment by belldandu** [comment]
Well the reason why most of those packages fail except opentri is because libtool hates dash being /bin/sh

**Comment by futurepr0n** [comment]
Sorry for my newbie-ness, but what can I do in lieu of that? dash being /bin/sh?? I don't understand entirely, any help is much appreciated

**Comment by liclac** [comment]
`/bin/sh` is actually a symlink, usually to a shell called `/bin/dash`, a shell which loads very,  very fast, but also doesn't support all the features a full-blown (but slower) shell like `/bin/bash`.

Normally, it's not a problem, but in this specific case, you'll have to change `sh` to be `bash` instead: https://wiki.debian.org/DashAsBinSh

**Comment by carstene1ns** [comment]
This one should be fixed nowadays.
