### ISSUE TITLE
Failed installing: openal opentri

### ISSUE THREAD

**Issue by BenMitnicK** [pspdev/psptoolchain#80]
At first I had this error

**Failed installing: angelscript libmikmod libpng openal opentri pixman SDL_image SDL_mixer**

I change /bin/bash now I have this error

Installation finished.
**Failed installing: openal opentri**
/usr/local/pspdev/bin added to your systems login scripts!

thx for your help

**Comment by different55** [comment]
Also seeing this issue on Debian Testing in 2018.

**Comment by JureTheMan77** [comment]
OpelAl's repository has changed, so changing it to 
download_and_extract http://www.openal-soft.org/openal-releases/openal-soft-$OPENAL_VERSION.tar.bz2
in openal.sh fixes the issue.

**Comment by sharkwouter** [comment]
This should be fixed for all libraries now, except for maybe OpenAL. For some reason OpenAL does not build on Debian 10, but it does on Ubuntu 19.10.
