### ISSUE TITLE
Upload Binaries

### ISSUE THREAD

**Issue by leonardoInf** [pspdev/psptoolchain#91]
I tried to compile the toolchain on Ubuntu and I didn't suceed (I have posted another Issue about this). 
According to [https://github.com/pspdev/pspsdk](link) you could download binaries at http://www.pspdev.org/ but the site is down and not available on wayback machine 
Can somebody upload the binaries for Ubuntu 64 bit?

**Comment by mondlos** [comment]
I've found the psp sdk binaries here: https://sourceforge.net/projects/devkitpro/files/devkitPSP/

**Comment by MichalLebeda** [comment]
they seem outdated :(

**Comment by mondlos** [comment]
well 2012... but I'm now using them and I haven't had any problems yet, everything works just fine (sometimes you need little tweaks like changing u32 to uint_32 etc.)

**Comment by carstene1ns** [comment]
I recently started working on a different approach to provide binaries using github actions.
If you are interested in the whole toolchain, you can find them here:
https://github.com/pspdev/pspdev/releases/latest

If you only want to get the pspsdk, it will show up here in the future:
https://github.com/pspdev/pspsdk/releases/latest

Please let me know if you find any issues. The release is currently without documentation. Just extract, add to $PATH and use.

**Comment by Yoti** [comment]
@carstene1ns pspdev is outdated and pspsdk still empty.

**Comment by carstene1ns** [comment]
Thank you for the notify, @Yoti. Unfortunately real life pressures have hindered me from working on this further in the last year.
I will see what I can do in the next days to get this mess cleaned up.

**Comment by Yoti** [comment]
@carstene1ns any news?

**Comment by wally4000** [comment]
Issue has since been resolved by fjtrujy

**Comment by Yoti** [comment]
@wally4000 so, where is the link to precompiled binaries?

**Comment by sharkwouter** [comment]
@Yoti you can find them over here: https://github.com/pspdev/pspdev/releases/tag/latest
