### ISSUE TITLE
SDL_Flip() does not refresh the screen, altough it sleeps for 5 secs. Source code below. 

### ISSUE THREAD

**Issue by bsdero** [pspdev/psptoolchain#93]
PSP_HEAP_SIZE_KB(20480);

int exit_callback(int arg1, int arg2, void *common) {
 sceKernelExitGame();
 return 0;
}

/* Callback thread */
int CallbackThread(SceSize args, void *argp) {
 int cbid = sceKernelCreateCallback("Exit Callback", exit_callback, NULL);
 sceKernelRegisterExitCallback(cbid);
 sceKernelSleepThreadCB();
 return 0;
}

/* Sets up the callback thread and returns its thread id */
int SetupCallbacks(void) {
int thid = sceKernelCreateThread("update_thread", CallbackThread, 0x11, 0xFA0, 0, 0);
 if(thid >= 0) { sceKernelStartThread(thid, 0, 0); }
return thid;
}

int SDL_main(int argc, char **argv){
  SetupCallbacks();
  SDL_Surface *PantallaV;
  SDL_Init(SDL_INIT_VIDEO);
  SDL_ShowCursor(0);
  PantallaV = SDL_SetVideoMode(480, 272, 32,SDL_HWSURFACE|SDL_DOUBLEBUF);
  SDL_Surface *imagen = IMG_Load("fondo.png");
  SDL_BlitSurface(imagen,NULL,PantallaV,NULL);
  SDL_Flip(PantallaV);
  SDL_Delay( 5000);
  SDL_FreeSurface(imagen);

  return 0;
}

**Comment by carstene1ns** [comment]
Not sure what is happening here, maybe something is not flushed or ready yet.
Got it to work by adding a short delay before `SDL_Flip()`.
This usually goes unnoticed, because you run the rendering in a loop.

**Comment by bsdero** [comment]
Tried this. Is still not working. 

int main(int argc, char **argv){
  SetupCallbacks();
  SDL_Surface *PantallaV;
  SDL_Init(SDL_INIT_VIDEO);
  //SDL_ShowCursor(0);
  SDL_Delay( 2000);
  PantallaV = SDL_SetVideoMode(480, 272, 32,SDL_HWSURFACE|SDL_DOUBLEBUF);
  SDL_Delay( 2000);
  SDL_Surface *imagen = IMG_Load("fondo.png");
  SDL_Delay( 2000);
  SDL_BlitSurface(imagen,NULL,PantallaV,NULL);
  SDL_Delay(2000);
  SDL_Flip(PantallaV);
  SDL_Delay( 5000);
  SDL_FreeSurface(imagen);
  return 0;
}

**Comment by bsdero** [comment]
What are the best SDL_SetVideoMode() arguments? Using C, not C++. Is ok to use main() as is, or would be better to use SDL_main() instead?

**Comment by bsdero** [comment]
Thanks in advance for the help, I really appreciate this. Just want to show off my own games to my nefews

**Comment by carstene1ns** [comment]
Maybe your `IMG_Load()` call returns an error, so the graphic is not loaded to the surface?

Here is a little demo: [sdl-demo.zip](https://github.com/pspdev/psptoolchain/files/1805349/sdl-demo.zip)
Not tested on hardware this time, but works in ppsspp emulator.

**Comment by bsdero** [comment]
That worked fine!!! Thanks a lot!!  👍 🥇
