### ISSUE TITLE
Cygwin issue: Can not build GNU MP

### ISSUE THREAD

**Issue by bsdero** [pspdev/psptoolchain#95]
checking for ferror_unlocked... configure: summary of build options:

  Version:           GNU MP 5.1.3
  Host type:         none-unknown-cygwin
  ABI:               standard
  Install prefix:    /opt/pspdev
  Compiler:          gcc
  Static libraries:  yes
  Shared libraries:  no

configure: If wine is installed, use make check TESTS_ENVIRONMENT=wine.
yes
checking for fflush_unlocked... yes
checking for fgetc_unlocked... yes
checking for fgets_unlocked... yes
checking for fileno_unlocked... yes
checking for fprintf_unlocked... no
checking for fputc_unlocked... yes
checking for fputs_unlocked... yes
checking for fread_unlocked... yes
checking for fwrite_unlocked... yes
checking for getchar_unlocked... yes
checking for getc_unlocked... yes
checking for putchar_unlocked... yes
checking for putc_unlocked... yes
checking whether abort is declared... yes
checking whether asprintf is declared... yes
checking whether basename is declared... yes
checking whether errno is declared... no
checking whether getopt is declared... yes
checking whether vasprintf is declared... yes
checking whether clearerr_unlocked is declared... yes
checking whether feof_unlocked is declared... yes
checking whether ferror_unlocked is declared... yes
checking whether fflush_unlocked is declared... yes
checking whether fgetc_unlocked is declared... yes
checking whether fgets_unlocked is declared... yes
checking whether fileno_unlocked is declared... yes
checking whether fprintf_unlocked is declared... no
checking whether fputc_unlocked is declared... yes
checking whether fputs_unlocked is declared... yes
checking whether fread_unlocked is declared... yes
checking whether fwrite_unlocked is declared... yes
checking whether getchar_unlocked is declared... yes
checking whether getc_unlocked is declared... yes
checking whether putchar_unlocked is declared... yes
checking whether putc_unlocked is declared... yes
checking for working alloca.h... yes
checking for alloca... yes
checking for ANSI C header files... (cached) yes
checking for nl_langinfo and CODESET... yes
checking whether NLS is requested... yes
checking for catalogs to be installed...  be ca da de el eo es fi fr id ja nl pt_BR ru sr sv tr uk vi zh_CN zh_TW be ca da de el eo es fi fr id ja nl pt_BR ru sr sv tr uk vi zh_CN zh_TW
checking for uchar...
checking for ld used by GCC... /usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../x86_64-pc-cygwin/bin/ld.exe
checking if the linker (/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/../../../../x86_64-pc-cygwin/bin/ld.exe) is GNU ld... yes
checking for shared library run path origin... done
checking for iconv... no, consider installing GNU libiconv
configure: updating cache ./config.cache
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: executing depdir commands
mkdir -p -- .deps
make[1]: Leaving directory '/home/argardu/psptoolchain.latest/psptoolchain/build/gcc-4.9.3/build-psp'
make: *** [Makefile:850: all] Error 2
../scripts/002-gcc-stage1.sh: Failed.

**Comment by carstene1ns** [comment]
I do not really think anyone can help with just this bit of information. Building the toolchain for cygwin is not really mentioned anywhere, so not sure this has been tested at all.

You should tell us how you setup your environment (setting some `$variable`s?) and post additional logfiles (`configure.log` of the mp directory would help quite a bit), etc.

One thing that seems odd though: on top the host type is `none-unknown-cygwin`, but it uses `x86_64-pc-cygwin` later on.

**Comment by carstene1ns** [comment]
Closing due to lack of information.
