### ISSUE TITLE
Error looking for readline in MacOS 10.13.x (High Sierra)

### ISSUE THREAD

**Issue by lowlevelsoul** [pspdev/psptoolchain#96]
After looking through the depends/check-dependancies.sh - it seems that the OSX branch calls check_header_nosys. This fails on the latest MacOS (or it may be the latest version of brew that's the issue) as readline is now contained in usr/include.

Brew tells me that readline is installed and usr/include is the the only place that I can find the header.

Suggested fix; call check_header instead of check_header_nosys.

**Comment by shockdesign** [comment]
@lowlevelsoul Running `brew link --force readline` seemed to fix the dependency issue are installing readline with brew.
