### ISSUE TITLE
Error compiling gcc with xcode 9.X

### ISSUE THREAD

**Issue by lowlevelsoul** [pspdev/psptoolchain#97]
I get the following error when building on Mac OS using Xcode 9.3;

"no member named 'fancy_abort' in namespace 'std::__1'; did you mean simply 'fancy_abort'?"

Full error is;

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/exception:180:5: error: 
      no member named 'fancy_abort' in namespace 'std::__1'; did you mean simply
      'fancy_abort'?
    _VSTD::abort();
    ^~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config:441:15: note: 
      expanded from macro '_VSTD'
#define _VSTD std::_LIBCPP_NAMESPACE
              ^
../../gcc/system.h:685:13: note: 'fancy_abort' declared here
extern void fancy_abort (const char *, int, const char *) ATTRIBUTE_NORETURN;
            ^
1 error generated.

**Comment by shockdesign** [comment]
I want to add that I'm receiving this as well, do we know which version of Xcode can compile this toolchain correctly?

Note: I've tried Xcode 9.4.1, Xcode 9.2 and Xcode 8.3.3, and all of them fail in various ways.

**Comment by AnalogMan151** [comment]
Having same issue here.

**Comment by ksallberg** [comment]
Anyone who managed to get past this?

**Comment by dbeef** [comment]
From now on we ship psptoolchain with GCC 9.3.0.

Could you report whether the problem still persists?

**Comment by ksallberg** [comment]
I have the following software:

* macOS Cataliona 10.15.3

* Xcode Version 11.3.1 (11C504)

This time it seems the compilation progresses further than before. I had to uncomment ncurses, zlib, readline from psptoolchain/depends/check-dependencies.sh

----

make[1]: *** [all-target-libgcc] Error 2
make: *** [all] Error 2
../scripts/002-gcc-stage1.sh: Failed.
ERROR: Could not run the toolchain script.


Not sure if this is relevant or not, but this appeared shortly before the compilation stopped:

xgcc: error: addsf3: No such file or directory
xgcc: error: subsf3: No such file or directory
make[2]: *** [addsf3.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [subsf3.o] Error 1
xgcc: error: negsf2: No such file or directory
make[2]: *** [negsf2.o] Error 1

**Comment by carstene1ns** [comment]
@ksallberg: I am able to reproduce. Problem is that the gcc configure script assumes gnu sed, which is not available on macOS by default.
Solution is to install it using homebrew and adding to the $PATH. I will add a patch for that in a bit.
