### ISSUE TITLE
`__builtin_allegrex_sync()` missing since gcc update

### ISSUE THREAD

**Issue by wodim** [pspdev/psptoolchain#98]
I'm hitting an internal compiler error using the toolchain provided by this repo. I was wondering if it would be possible to change to other version of gcc, maybe a previous one.

If you're curious this is the repo of the application that causes the ICE: https://github.com/phoe-nix/TempGBA4PSP-mod - Very straightforward to compile, also raises an error because of strict-aliasing rules. That's fixable, but an ICE is not. (As far as I know.)

**Comment by carstene1ns** [comment]
The patch for gcc 4.6.4 is still in the repo, this should switch to it:
```sh
sed 's/4.9.3/4.6.4/' -i scripts/00?-gcc-stage?.sh
```

Just tested with 5.4.0, `__builtin_allegrex_sync()` is also broken there.

**Comment by wodim** [comment]
Thank you for taking time to test this. Can you confirm the repo I 
linked to compiles correctly under 4.6.4? I'm away from my computer now.

**Comment by bmaupin** [comment]
I just got the same error with GCC 8.3.0 provided by https://github.com/mrneo240/psptoolchain, also trying to compile https://github.com/libretro/TempGBA-libretro

```
$ make
psp-gcc -c -o mips_stub.o mips_stub.S -G0 -march=allegrex -mfp32 -mgp32 -mlong32 -mabi=eabi -fomit-frame-pointer -fstrict-aliasing -falign-functions=32 -falign-loops -falign-labels -falign-jumps -Wall -Wundef -Wpointer-arith -Wbad-function-cast -Wwrite-strings -Wsign-compare -D__LIBRETRO__ -DPSP -D_PSP_FW_VERSION=371 -O3
psp-gcc -c -o cpu.o cpu.c -G0 -march=allegrex -mfp32 -mgp32 -mlong32 -mabi=eabi -fomit-frame-pointer -fstrict-aliasing -falign-functions=32 -falign-loops -falign-labels -falign-jumps -Wall -Wundef -Wpointer-arith -Wbad-function-cast -Wwrite-strings -Wsign-compare -D__LIBRETRO__ -DPSP -D_PSP_FW_VERSION=371 -O2 -I. -I/home/user/Desktop/pspdev/psp/sdk/include
during RTL pass: expand
cpu.c: In function ‘translate_block_arm’:
cpu.c:3302:3: internal compiler error: in maybe_gen_insn, at optabs.c:7276
   __builtin_allegrex_sync();
   ^~~~~~~~~~~~~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
Makefile:67: recipe for target 'cpu.o' failed
make: *** [cpu.o] Error 1

$ psp-gcc --version
psp-gcc (GCC) 8.3.0
```

**Comment by joel16** [comment]
It seems like some patch got rid of a lot of sceAllegrex* functions. I made an issue about another one that was missing as well.

**Comment by bmaupin** [comment]
> Can you confirm the repo I linked to compiles correctly under 4.6.4?

@wodim I rebuilt the psptoolchain with gcc 4.6.4 and I was able to build https://github.com/libretro/TempGBA-libretro, so I'm guessing yours should work fine too now.

I had to build it on an Ubuntu 16.04 container since I wasn't able to compile gcc 4.6.4. I guess the libraries or gcc is too new.

**Comment by bmaupin** [comment]
Until this is fixed I went ahead and built a docker image with gcc 4.6.4 so we can use it to build TempGBA4PSP:

https://hub.docker.com/r/bmaupin/pspdev

**Comment by dbeef** [comment]
Closing this issue as the PR with GCC 9.3.0 update has just been merged to master.

https://github.com/pspdev/psptoolchain/pull/111

**Comment by blackrose28** [comment]
@dbeef : This issue need to reopen because even with gcc 9.3.0, TempGBA4PSP still failed to build at exact same file and line number

**Comment by Sir-Fortesque** [comment]
Since I've been working on a fix for missing `__builtin_allegrex_wsbh` and `__builtin_allegrex_wsbw` I had a look at `__builtin_allegrex_sync` too. I've implemented a fix for `__builtin_allegrex_wsbw`, gcc compiles so too does a template application referencing the builtin command although untested (running on hardware).  https://github.com/Sir-Fortesque/psptoolchain/commit/94d018dc8f953da7044cc3f54fe14686864bf06d

I had a look through gcc and noticed that from my knowledge (limited) all the required components look there. 

It appears to be a deeper issue than just an undefined insn.

```bash
main.c: In function ‘main’:
main.c:32:3: internal compiler error: in maybe_gen_insn, at optabs.c:7394
   32 |   __builtin_allegrex_sync();
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
0x571905 maybe_gen_insn(insn_code, unsigned int, expand_operand*)
	../../gcc/optabs.c:7394
0x96b33c maybe_expand_insn(insn_code, unsigned int, expand_operand*)
	../../gcc/optabs.c:7404
0xd2c0d5 mips_expand_builtin_insn
	../../gcc/config/mips/mips.c:17049
0xd2c590 mips_expand_builtin_direct
	../../gcc/config/mips/mips.c:17107
0xd2c951 mips_expand_builtin
	../../gcc/config/mips/mips.c:17326
0x67a884 expand_builtin(tree_node*, rtx_def*, rtx_def*, machine_mode, int)
	../../gcc/builtins.c:7236
0x791776 expand_expr_real_1(tree_node*, rtx_def*, machine_mode, expand_modifier, rtx_def**, bool)
	../../gcc/expr.c:11030
0x69a62e expand_expr
	../../gcc/expr.h:279
0x69a62e expand_call_stmt
	../../gcc/cfgexpand.c:2724
0x69a62e expand_gimple_stmt_1
	../../gcc/cfgexpand.c:3691
0x69a62e expand_gimple_stmt
	../../gcc/cfgexpand.c:3850
0x69f2bf expand_gimple_basic_block
	../../gcc/cfgexpand.c:5890
0x6a166e execute
	../../gcc/cfgexpand.c:6513
```

Like `_builtin_allegrex_sync()` I'm also having issues solving `_builtin_allegrex_wsbh()` which seems to stem from upstream gcc changes to support the patched in insn for the mips platform. Not sure the best approach from here.

**Comment by fjtrujy** [comment]
@davidgfnet is that issue solved after the latest changes in the toolchain?

**Comment by wally4000** [comment]
I'll go ahead and mark this as resolved as from what I've seen builtins work now, if it's still an issue please reopen :)

**Comment by davidgfnet** [comment]
Oh yeah sorry, this is definitely resolved. Thanks!
