### ISSUE TITLE
Failed installing: bzip2 openal opentri

### ISSUE THREAD

**Issue by raymi6** [pspdev/psptoolchain#99]
Good evening,

So basically everytime I try to run the toolchain I end up with those three that won't install and I can't grasp where it goes wrong in the process. This is after I changed /bin/sh to bash instead of dash and also changing the download path in openal.sh that needed to be changed. Bzip2 is installed on my computer if it helps. 

Thanks

Edit : I did manage to find how it goes wrong. Here it is 

> Cloning into 'psplibraries'...
> ssh: connect to host github.com port 22: Connection timed  out
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> Cloning into 'psplibraries'...
> remote: Enumerating objects: 919, done.
> remote: Total 919 (delta 0), reused 0 (delta 0), pack-reused 919
> Receiving objects: 100% (919/919), 466.50 KiB | 301.00 KiB/s, done.
> Resolving deltas: 100% (510/510), done.
> angelscript already installed
> ls: cannot access '/usr/local/pspdev/psp/lib/libbz2.a': No such file or directory
> ls: cannot access '/usr/local/pspdev/psp/include/bzlib.h': No such file or directory
> --2018-10-25 09:02:28--  http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz
> Resolving www.bzip.org (www.bzip.org)... 
> Connecting to www.bzip.org (www.bzip.org)|... connected.
> HTTP request sent, awaiting response... 301 Moved Permanently
> Location: http://www.bzip.org [following]
> --2018-10-25 09:02:29--  http://www.bzip.org/
> Reusing existing connection to www.bzip.org:80.
> HTTP request sent, awaiting response... 200 OK
> Length: unspecified [text/html]
> Saving to: 'bzip2-1.0.6.tar.gz'
> 
> bzip2-1.0.6.tar.gz        [ <=>                    ]  17.12K  --.-KB/s    in 0.02s   
> 
> 2018-10-25 09:02:29 (1011 KB/s) - 'bzip2-1.0.6.tar.gz' saved [17526]
> 
> Extracting bzip2-1.0.6.tar.gz...
> 
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> Failed installing bzip2!

Does that mean that the .tar.gz is not really gzipped and just compressed using tar ?

**Comment by raymi6** [comment]
The problem with bzip2 was solved by changing the download source in bzip2.sh with the following one : https://bintray.com/conan/Sources/download_file?file_path=bzip2-$BZIP2_VERSION.tar.gz

It's probably just a temporary solution though, I doubt it will last.

**Comment by liclac** [comment]
@raymi6 Could you send a PR that updates the script?

**Comment by suicvne** [comment]
I had issues buliding openal earlier...is a script tweak really all it needs? I had actual errors when I tried to include it in a project but not when building it...something about unable to find pthread despite psp-pthread being installed and linked against.

**Comment by raymi6** [comment]
@suicvne  When I tried compiling it again on another machine after a month, it seemed like the original download sources of both the bzip2 and openal worked, meaning they could install properly. However, and I have posted this in another issue, I still have the problem you describe with pthread, Haven't found a solution to that either :/
